var D2R_namespacePrefixes = {
    "jps": "https://jpsearch.go.jp/term/property#",
    "schema": "http://schema.org/",
    "type": "https://w3id.org/hi/api/term/type/",
    "chname": "https://w3id.org/hi/api/entity/chname/",
    "place": "https://w3id.org/hi/api/entity/place/",
    "time": "https://w3id.org/hi/api/entity/time/",
    //"work": "https://jpsearch.go.jp/entity/work/",
    //"role": "https://jpsearch.go.jp/term/role/",
    //"keyword": "https://jpsearch.go.jp/term/keyword/",
    "skos": "http://www.w3.org/2004/02/skos/core#",
    //"gvname": "https://jpsearch.go.jp/entity/gvname/",
    //"ncname": "https://jpsearch.go.jp/entity/ncname/",
    //"ncplace": "https://jpsearch.go.jp/entity/ncplace/",
    //"series": "https://jpsearch.go.jp/entity/series/",
    "xsd": "http://www.w3.org/2001/XMLSchema#",
    rdf: 'http://www.w3.org/1999/02/22-rdf-syntax-ns#',
    rdfs: 'http://www.w3.org/2000/01/rdf-schema#',
    owl: 'http://www.w3.org/2002/07/owl#',
    dct: "http://purl.org/dc/terms/",
    genji: "https://w3id.org/kouigenjimonogatari/api/property/",
    "prop-ja": "http://ja.dbpedia.org/property/",
    "emperor": "https://w3id.org/hi/api/entity/emperor/",
    "kani": "https://w3id.org/hi/api/term/kani/",
    "role": "https://w3id.org/hi/api/term/role/",
    "keyword": "https://w3id.org/hi/api/term/keyword/",
    "jps-type":"https://jpsearch.go.jp/term/type/",
    "jps-time":"https://jpsearch.go.jp/entity/time/",
    "hi":"https://w3id.org/hi/api/term/property#"
};

